feat: add buttons in data
AlenaMikalaeynaLisava/jet-start pull request #1
Opened 2021-04-18 14:07 UTC by AlenaMikalaeynaLisava

1. lesson3-1
2.
![image](https://user-images.githubusercontent.com/63248586/115148484-7d0d5200-a068-11eb-8b0b-52efc6874c5f.png)
3. Facing problems with toolbar in data.js folder

2021-04-19 00:19 UTC, HelgaListopad requested changes
В дополнение к комментам в ревью

- больше не делай прямых коммитов на мастер (имеется в виду [вот этот](https://github.com/AlenaMikalaeynaLisava/jet-start/commit/97e2259bddf1349d4a798da139df628fd11d49cd) коммит). Это не поправилам, плюс в ревью pull request я могу оставить комментарии только под тем, что в этот PR входит.
- в top.js меню стоит переделать меню с простых `href` на то, что предлагает Jet. Это либо [самостоятельный](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/navigation#4-view-show) вызов `show` по `onItemClick` (в зависимости от ситуации - от app или от view), либо [Menu Plugin](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/plugins#menu-plugin), как изначально было в jet-start.
- К проекту подключён линтер (файл `.eslintrc.json`)
Перед тем, как отдавать задание на ревью, обязательно запускай его через консоль - это позволит отследить и исправить мелкие синтаксические ошибки, неиспользованные переменные, пробелы вместо табуляции, разные кавычки и другие вещи.
Как запустить
```
// посмотреть на ошибки
npm run lint
// посмотреть и исправить автоматически то, что можно 
npm run lint -- --fix
```
Потом исправить оставшееся вручную и запушить код. После этого отдавать на ревью.
Не забывай про этот слайд.)
https://slides.com/ihelga/webixjet-views/#/34

2021-04-19 00:19 UTC, HelgaListopad commented on sources/myapp.js
> +import {JetApp, UrlRouter,EmptyRouter, HashRouter } from "webix-jet";
UrlRouter не используется - нужно удалить (это есть и в сообщениях линтера)

2021-04-19 00:19 UTC, HelgaListopad commented on sources/views/data.js
> +				{ view:"toolbar", cols:[
Тут структуру лучше поменять.
Сейчасу тебя переиспользуется только таблица, а вот ниже - один тулбар на двоих, в котором используется крайне сложный путь нахождения активной таблицы.
Чтобы упростить дело, можно переиспользовать JetView, в котором будет layout с таблицей и тулбаром, который будет привязан только к своей таблице (что резко упрощает дело).


Также в задании
> *provides add/delete/update functionality*

Update тут никак не реализован. Это может быть эдитор в колонке таблицы.

2021-04-19 00:19 UTC, HelgaListopad commented on sources/views/contacts.js
> -    //  view.queryView("list").parse(contacts);
Этот вариант для приложения лучше подходит, чем `data` - так можно поделить конфигурацию UI и загрузку данных.

2021-04-20 13:46 UTC, AlenaMikalaeynaLisava commented on sources/views/contacts.js
> -    //  view.queryView("list").parse(contacts);
![image](https://user-images.githubusercontent.com/63248586/115406489-e7a0c800-a1f7-11eb-915a-1287eb2d8092.png)

2021-04-20 17:44 UTC, HelgaListopad commented on sources/views/contacts.js
> -    //  view.queryView("list").parse(contacts);
Вместо скриншотов достаточно написать, что ты это исправила - само решение я увижу в коммитах.)

2021-04-20 18:04 UTC, HelgaListopad requested changes

2021-04-20 18:04 UTC, HelgaListopad commented on sources/views/gridview.js
> +							var table = this.getParentView().getParentView().queryView("datatable");
Череда `getParentView` - однин из самых ненадёжных способов добраться до какого-то виджета. 
Такая запись станет неактуальной, как только поменяется структура layout (что запросто может случиться в дальнейшей разработке).
Использовать эту запись стоит только тогда, когда нет альтернатив (а они обычно есть).

Лучше всего в такой ситуации использовать `localId` 
Слайд: https://slides.com/ihelga/webixjet-views/#/31
Документация (пункт 5): https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/referencing-views

Работает как обычное `id`, но не глобально, а только внутри и от экземпляра класса, в котором задано.
```
this.$$("localListId") // где this - JetView
```
Дополнение: второй условно-универсальный вариант - `queryView` вверх или вниз по иерархии UI (обрати внимание на раздел [Details](https://docs.webix.com/api__link__ui.view_queryview.html)), но здесь это всё-таки не так хорошо подходит.

2021-04-20 18:04 UTC, HelgaListopad commented on sources/views/gridview.js
> +							var table = this.getParentView().getParentView().queryView("datatable");
Изменить `.getParentView().getParentView()` нужно везде, где это встречается.

2021-04-20 18:04 UTC, HelgaListopad commented on sources/views/gridview.js
> +							table.refresh();
Всю эту кнопку можно убрать, так как по заданию refresh здесь не нужен, да он и не делает ничего полезного.

2021-04-20 18:04 UTC, HelgaListopad commented on sources/views/gridview.js
> +		view.queryView("datatable").getColumnConfig("Name").editor = "text";
А почему эдитор не задан в самой конфигурации колонки?
Если есть кастомные настройки, `autoConfig` нужно заменить на полноценное описание `columns`.

2021-04-20 18:04 UTC, HelgaListopad commented on sources/views/gridview.js
> +		view.queryView("datatable").parse(this._gridData);
При переходе на `localId` будет иметь смысл пользоваться только им для того, чтобы код был однообразным и было чёткое понимание того, что все операции относятся в одному и тому же компоненту.
Хоть это и правильное решение, я попрошу поменять и его тоже.

2021-04-22 07:32 UTC, HelgaListopad commented on sources/views/gridview.js
> +		view.queryView("datatable").getColumnConfig("Name").editor = "text";
Снимаю вопрос, так как сейчас всё работает хорошо

2021-04-22 07:32 UTC, HelgaListopad approved these changes

2021-04-22 07:32 UTC, merged